### ISSUE TITLE
Hide report columns on no data

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#106]
Campaign Performance and Invoice reports need the column headers hidden when there is no data present in the report

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/109

**Comment by harrisward** [comment]
Feature Branch: https://github.com/ivylabs/suitecrm-analytics/tree/feature-106

**Comment by fraserward** [comment]
Tested and working

**Comment by harrisward** [comment]
Fraser tested and confirmed
