### ISSUE TITLE
Format Sales Performance Dashboard Pie Chart Tooltips

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#107]
The Tooltips need formatting. Most likely a CDA output column change or possible CCC properties

**Comment by harrisward** [comment]
Fixed the Pie Chart hover tooltips in the Sales Performance Dashboards to remove names like "USER_NAME" with "Agent Name"

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/112
Feature Request: https://github.com/ivylabs/suitecrm-analytics/tree/feature-107

**Comment by fraserward** [comment]
Checked.  Names fixed.
