### ISSUE TITLE
Add documentation about CST URL Generation

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#108]
We need to tell the end user how they can easily get the URL for a solution file so they can configure the CST

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/114
Feature Branch: https://github.com/ivylabs/suitecrm-analytics/tree/feature-108

**Comment by fraserward** [comment]
Files is updated and located in correct place.
