### ISSUE TITLE
Update Invoice Report

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#110]
Add the Report Status to the report.

The Invoice should display one of the three possible invoice status:
Paid - Green - #87a049
Unpaid Red - #a1414f
Cancelled - Grey - #cccccc

The text field should sit below the invoice name with the same font size as the invoice name text field

Add the Invoice Date and Invoice Due Date fields underneath the Invoice status field. Use the same formatting as the Address fields

Invoice Date : 01-02-2020
Due Date : 31-01-2020

**Comment by harrisward** [comment]
Lets discuss where this should be on the report

**Comment by fraserward** [comment]
Also perhaps dare field for raised paid overdue

**Comment by fraserward** [comment]
updated report format.

**Comment by harrisward** [comment]
Tested and looks good

**Comment by fraserward** [comment]
Fix required . See #154
