### ISSUE TITLE
Fix Invoice Discount column

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#111]
The invoice discount column is pointing to INVOIVE_LINE_DISCOUNT_VALUE but should instead be pointing to INVOIVE_LINE_DISCOUNT_AMOUNT

**Comment by harrisward** [comment]
The report should now show discount on monetary value and not percentage values

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/113
Feature Branch: https://github.com/ivylabs/suitecrm-analytics/tree/feature-111

**Comment by fraserward** [comment]
Tested.  Working.
