### ISSUE TITLE
Add Deleted Records filter to Reports

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#117]
We need to add a filter to all existing reports that allows the end user to show or hide deleted records in the report output.

We can do this by added a new Table Data Source and Parameter to the report and passing the result into the query

The Deleted Filter should be displayed after the Show Parameters Filter.
The title should be "Deleted Records"
The Options should be "Show" or "Hide" - Show will be default

**Comment by fraserward** [comment]
reports updated

**Comment by harrisward** [comment]
Tested
