### ISSUE TITLE
Create new reporting template

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#12]
Create a new reporting template that includes predefined parameters based on a shared CDA data source

**Comment by samus-aran** [comment]
Is this the custom Report Template I can see in the reports?

![FireShot Capture 003 - SuiteCRM Analytics - GroupedLeadPerformance -Report](https://user-images.githubusercontent.com/4041275/71012683-627b3f80-20e7-11ea-8985-19313c48c38c.png)

**Comment by harrisward** [comment]
I will write up a top tip on editing the styles.

Need to test the date selectors

**Comment by harrisward** [comment]
> Is this the custom Report Template I can see in the reports?
> 
> ![FireShot Capture 003 - SuiteCRM Analytics - GroupedLeadPerformance -Report](https://user-images.githubusercontent.com/4041275/71012683-627b3f80-20e7-11ea-8985-19313c48c38c.png)

No. The Reporting Template is a base template that users can load to build new reports on
