### ISSUE TITLE
Typo in CDA Date queries 

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#145]
Need to correct CDA queries from YYYY-DD to YYY-MM and update reports parameters
![image](https://user-images.githubusercontent.com/58402250/111831631-8f6c6280-88e7-11eb-9e4b-8e1a6ab1fc97.png)

**Comment by harrisward** [comment]
Need to make sure we edit the cda Queries via by editing the CDE files that generate the cda files

**Comment by fraserward** [comment]
Updated 'FILTERS' CDE file for:

1. Cases 
      Created, Modified, Closed

2. Opportunities
      Created, Closed

3. Activity Date Filter

4. Sale Report Date Filter

No other queries were referencing YYYY-DD to YYYY-MM.

CDE then updated CDA - checked and correct.

Edited 5 Report files as the date selecting parameters were point to old values of YYYY-DD and were required to be moved to YYYY-MM

modified these files:

        modified:   ../install/solution/public/SuiteCRM+Analytics/Reports/AccountOpportunityValue.prpt
	modified:   ../install/solution/public/SuiteCRM+Analytics/Reports/AgentCasePerformance.prpt
	modified:   ../install/solution/public/SuiteCRM+Analytics/Reports/AgentOpportunityActivity.prpt
	modified:   ../install/solution/public/SuiteCRM+Analytics/Reports/AgentOpportunityPerformance.prpt
	modified:   ../install/solution/public/SuiteCRM+Analytics/Reports/AgentSalesReport.prpt
	modified:   ../install/solution/public/SuiteCRM+Analytics/System/Resources/CDA/FILTERS.cda
	modified:   ../install/solution/public/SuiteCRM+Analytics/System/Resources/CDA/FILTERS.cdfde

**Comment by fraserward** [comment]
NOTE:  5 PRPT report files were also updated on this ticket
