### ISSUE TITLE
Hide Data Headers and Totals on Agent Opportunity Activity Report

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#149]
When there is no data in the report we should hide the headers and group footers (totals) in the report.

Refer to existing reports **visible** function to understand the formula to hide other elements

See the attached screenshot:

![image](https://user-images.githubusercontent.com/6827832/111852092-9c03b180-890d-11eb-900d-409ca42af49f.png)

**Comment by fraserward** [comment]
report updated

**Comment by fraserward** [comment]
Remove extra line blank space on no data

**Comment by harrisward** [comment]
Tested and looks good
