### ISSUE TITLE
Add FUNC_TOTAL_ROWS to report template

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#151]
Copy this function from an existing report to the report template.

Make sure this argument is also added to the header and footer details band =if([FUNC_TOTAL_ROWS]=0;"false";"true") .  This will remove the headers and footers when no data is present.

![image](https://user-images.githubusercontent.com/58402250/112013752-32102580-8b22-11eb-9684-b647f37528ce.png)

**Comment by harrisward** [comment]
Tested
