### ISSUE TITLE
Update JDBC driver for MySQL 8.0.23-0

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#171]
Ubunto 20.04 no longer supports 'MySQL 5.7.X.'. Replaced with' MySQL 8.0.23'

With this new version of MySQL the JDBC drivers used with the Analytics no longer work.

To fix this, remove from the analytics installation:

mysql-connector-java-5.1.17.jar  &
mysql-connector-java-5.1.36.jar 

Use instead:

mysql-connector-java-5.1.47.jar

**Comment by fraserward** [comment]
Tested on local Ubunto 18 and remote Ubunto 20 machine.  Working

**Comment by harrisward** [comment]
Tested in 18.04
