### ISSUE TITLE
Disable Report Export Button on Activities Dashboard

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#182]
When no Agents have been selected on the activities table in the Opportunity Activities Dashboard then the export button should be disabled to prevent a user from exporting and empty report

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/191

**Comment by fraserward** [comment]
When ticking a box in the 'details agent listing' the export button highlights and can be used (this is correct).  If then going on to click a dot in the 'total activities & opportunities by agent' graph, the export remains highlighted even though no agents are selected on the 'detailed agents listing' field.

**Comment by fraserward** [comment]
Tested.  Working

**Comment by johnM2401** [comment]
Looks good to me

Selected records appear to be cleared out when appropriate, so user cannot export nothing.
(Resetting Filters / Drilldown by clicking on Chart item / Refresh Page)
