### ISSUE TITLE
Investigate Added extracted PRPT to the github repo

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#188]
**Is your feature request related to a problem? Please describe.**
We are not able to track PRPT files in github as they are zip files. This means its hard to track XML code changes

**Describe the solution you'd like**
Store the contents of the PRPT (zip) file directly into the github repository and zip them back into PRPTs at build time

**Describe alternatives you've considered**
Store them as PRPTs

**Comment by harrisward** [comment]
With this solution we will need to extract each PRPT before we commit it to github. We will then do a few tests like editing a DB connection detail in the PRPT, extract and push to github again to make sure we can track the changes.

Finally, when it comes to BUILD the server we need to repackages (zip) each PRPT and test them in the BIServer.

If this works we can use it a solution going forward.

**Comment by harrisward** [comment]
Created an initial script that will loop through prpt extracted folders and zip up the reports. Still needs more testing

**Comment by harrisward** [comment]
Stashed

**Comment by fraserward** [comment]
Tested and working
