### ISSUE TITLE
Invoice Visual bug

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#190]
**Describe the bug**
There is an issue with the visual output on certain invoices in at least HTML Stream output. At the bottom of invoice 157 the horizontal bar is right up under the table. See the screenshot

**Component
What component does this bug relate to?
1. Report

**Solution File
invoice.prpt

**To Reproduce**
1. Run the invoice Report
2. Select Unpaid

**Expected behavior**
The formatting looks correct

**Screenshots**

![image](https://user-images.githubusercontent.com/6827832/114708560-68a51e80-9d23-11eb-85d6-4ef48e5c887f.png)

**Comment by fraserward** [comment]
Cannot replicate bug.  Perhaps browser issue.
