### ISSUE TITLE
Opportunities Activities Dashboard - not refreshing correctly

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#195]
Bug:

When changing the date range for this dashboard the charts and graphs update but the 'Detailed Agent Listing' does not update.  

**Component

Dashboard

**Solution File

OpportunityActivitiesDashboard.wcdf

**To Reproduce**

Have 30 days in the date range and you click on one dot to select one agent then one agent is displayed in the 'Detailed Agent Listing' (DAL) field.  If you then go on to change the date range to 12 month then the graphs all update on pressing 'refresh' but the 'DAL still only show the one agent but the 'Total Activities & Opportunities By Agent' (TAOBA) graphs have all dots highlighted.

**Expected behavior**

Make it so the TAOBA table when refreshing reflects the agent selected in the DAL (the correct dots highlighted).
or 
Have the DAL reset on refresh to show all agents in the TAOBA.

**Screenshots**

![dashboard](https://user-images.githubusercontent.com/58402250/114886184-dc642b80-9df6-11eb-980e-2da8fc746642.png)

**Desktop (please complete the following information):**

Ubunot 18
Chrome

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/211

**Comment by fraserward** [comment]
Tested. Working.
