### ISSUE TITLE
Enhance the Data Exporter Lead Report

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#198]
**Is your feature request related to a problem? Please describe.**
The Lead Export solution in the Data Exporter only has one parameter when the user chooses to export. We need to add additional options for Leads as we have in the Cases Export

**Describe the solution you'd like**
Add the following Parameters:
- Lead Status
- Lead Converted
- Lead Created Date
- Lead Converted Date
- Campaign
- Campaign Status
- Campaign Type
- Assigned Agent

**Comment by fraserward** [comment]
Updated the LEAD & CASE Export transformation. and Export Job file to include Lead parameters.  Created server CDA files for the parameters.

CASE Export file updated excel write step to not write to file with no data.  This has fixed issue with multiply excel result overwriting each other but a issue needs to be resolved on ticket... #206

**Comment by johnM2401** [comment]
Issue raised for this here:
https://github.com/ivylabs/suitecrm-analytics/issues/261
