### ISSUE TITLE
Report charts not rendering on new servers

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#2]
On the DEV server charts render fine. For whatever reason the charts are not rendering on newly packaged servers. This may be due to a hard coded value in the report chart reference.

It could also possibly be related to spaces in the name of the repo solution folder like "SuiteCRM Analytics". We need to test if the correct URL is being passed to the report

**Comment by samus-aran** [comment]
This looks like this is completed.
