### ISSUE TITLE
Remove Select option from Cases Export

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#201]
**Is your feature request related to a problem? Please describe.**
Data Exporter for the Cases Export has a Select Case filter. This filter lists ALL cases and allows the user to select a single case to export. I don't thin this is useful. Also this selector is very large as it has a single option per case

**Describe the solution you'd like**
We need to remove this selector from the Case Export solution

**Additional context**
To remove it we need to remove the parameter from the Get Case Data transformation and the SQL in the table input step. We also need to edit the data export parameter mapping in suitecrm data integration. I have created a ticket for that here:
https://github.com/ivylabs/suitecrm-data-integration/issues/154

**Comment by fraserward** [comment]
Updated the SQL statement in the transformation and the parameters in both the job and the transformation

**Comment by harrisward** [comment]
Tested
