### ISSUE TITLE
Data Exporter refresh issue

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#202]
**Describe the bug**
When a user swaps between exports to run the dynamic selector generation code is flawed and does not refresh correcty

**Component
What component does this bug relate to?
2. Dashboard
6. Other

**Solution File
Data Exporter

**Comment by johnM2401** [comment]
Hey @harrisward 
Do you have any recommendations on how to go about testing this one?
(Specifically with what is meant by the dynamic selector "not refreshing correctly"?)

Do you feel the following would suffice, for testing?:
- Select Lead Data Export
- Perform Export, ensure Lead data returned is accurate
- Switch to Case Export
- Perform Export, ensure Case data returned is accurate
- Change parameters on Case Data Export
- Perform Export and ensure data returned is accurate

Or is there anything else you'd recommend looking out for?

**Comment by harrisward** [comment]
@johnM2401  Thats exactly it. Before when we switched reports the second report chosen would fail at parsing parameters. It both reports run with parameters and the data looks good then we are good
