### ISSUE TITLE
Modify original setup database config file

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#204]
**Is your feature request related to a problem? Please describe.**
We need to disable SSL on the JDBC connection string. We see MySQL errors on MySQL 5.7 in Ubuntu 20.04

**Describe the solution you'd like**
Add ?useSSL=false to both JDBC connections in the install/suitecrm-analytics/tomcat/webapps/suitecrmanalytics/META-INF/context.xml file

**Comment by harrisward** [comment]
Added to the install files and the changes are present after the setup script has been run, No errors in ubuntu 18.04 but not test in ubuntu 20.04

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/214

**Comment by fraserward** [comment]
Tested. Working.

**Comment by Mac-Rae** [comment]
Assessed and confirmed to work! :+1:

**Comment by johnM2401** [comment]
Much Appreciated @Mac-Rae !

Moving to Done
