### ISSUE TITLE
Parameters selected on data export produce no result

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#206]
**bug**
As excel output wait for rows.  If parameters selected = no returnable rows then on clicking export you are taken to error page.

URL returns webpage with ' {"result":true,"exitStatus":0,"nrRows":0,"nrErrors":0}' 

**Component**
2. Dashboard

**Solution File**
getCaseData.ktr
getLeadData.ktr

**To Reproduce**
Select whatever parameters you like to get a returned result of nothing and click export

**Expected behavior**
A no data message
or
Disable the EXPORT button

**Comment by fraserward** [comment]
Detect empty rows step?

**Comment by fraserward** [comment]
Detect Empty Stream step will not work as it will take us back to both excel writers creating excel files.

Perhaps dashboard edit to disable button when no data to export would be the best course of action.

**Comment by harrisward** [comment]
See attached transformation. It shows that an excel sheet can be triggered depending on if the stream has data or not. Set the generation rows steps to output either 1 or 0 rows to test the functionality. Also refer to the detect streams step here: https://wiki.pentaho.com/display/EAI/Detect+empty+stream

**Comment by fraserward** [comment]
Updated transformation to allow 'no data' reports  
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/212

**Comment by harrisward** [comment]
Tesed
