### ISSUE TITLE
Move DATA_EXPORT_PARAMETERS_MAPPING DDL from SuiteCRM Data Integration

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#207]
**Is your feature request related to a problem? Please describe.**
The DATA EXPORT PARAMETERS MAPPING DDL lives in SuiteCRM Data Integration. This means that SuiteCRm Analytics has a  dependency on this project. We need to move the DDL / Database tables over to Hypersonic

**Describe the solution you'd like**
Move the data and create the DDL in a hypersonic database. Use the IvyUD plugin as an example

**Comment by harrisward** [comment]
Moved the parameter mapping over to SuiteCRM Analytics. Make sure the Data Exporter still works after a fresh install. You should be able to drop the Data Warehouse DATA_EXPORT_PARAMETER_MAPPING table now and the exporter will still work.

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/237

**Comment by fraserward** [comment]
Tested. Working.
