### ISSUE TITLE
Agent Opportunity Activity Report - Update USER_FULL_NAME

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#209]
**Describe the bug**
Report needs to be updated in the header and on the totals to use 'USER_FULL_NAME' instead of 'USER_NAME'

**Component**
Dashboard

**Solution File**
Agent Opportunity Activity Report

**To Reproduce**
Run the report

**Expected behavior**
User Name to be Pascal Case and space between first and last name

**Screenshots**

![image](https://user-images.githubusercontent.com/58402250/115541320-84ae4000-a28e-11eb-8e5c-724455ca168d.png)

**Comment by harrisward** [comment]
Can confirm the bug. Ready to fix

**Comment by fraserward** [comment]
Updated PRPT to use USER_FULL_NAME
