### ISSUE TITLE
Add CCG minimal sample chart

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#218]
**Is your feature request related to a problem? Please describe.**
Not a problem but I want to include a CGG chart sample that has been written by hand. This is a much more efficient than using the CDE to generate charts

**Describe the solution you'd like**
A simple CGG Chart sample that uses shared JS resources like branding

**Describe alternatives you've considered**
Using the CDE to generate CGG charts

**Additional context**
None

**Comment by harrisward** [comment]
Added CGGCHART.js to the System/Resources/SAMPLES directory. This should render a simple chart

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/219

**Comment by fraserward** [comment]
Tested. Working.
