### ISSUE TITLE
Add Module Dimension to Activities Cube

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#220]
**Is your feature request related to a problem? Please describe.**
Add a "Module" shared dimension to the suitecrm analytics cube

**Comment by harrisward** [comment]
Added new Module Dimension to the Activities Cube in the Mondrian schema

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/221

**Comment by fraserward** [comment]
Tested. Working.
