### ISSUE TITLE
Add a new Opportunity Data Export solution

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#222]
**Is your feature request related to a problem? Please describe.**
TBD

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
TBD

**Comment by harrisward** [comment]
Review Specification: https://ivy-is.atlassian.net/wiki/spaces/SA/pages/1846935561/Opportunity+Data+Export

**Comment by fraserward** [comment]
CDA's updated.  Export Job parameters updated.  Opportunities Export Transformation created.  Activities, Sales Transformations fixed No Style excel sheets (start at A6)

Pull Request:  https://github.com/ivylabs/suitecrm-analytics/pull/236

**Comment by johnM2401** [comment]
Looks good, Each parameter appears to return results as expected, even when multiple parameters are set.
Results match with the Account Opportunity Value Report.
