### ISSUE TITLE
Add a new Activity Data Export solution

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#223]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harrisward** [comment]
Review specifications: https://ivy-is.atlassian.net/wiki/spaces/SA/pages/1846935613/Activity+Data+Export

**Comment by fraserward** [comment]
updated CDAs ExcelData Job. Created Activity Data Export transformation

Pull Request : https://github.com/ivylabs/suitecrm-analytics/pull/233

**Comment by fraserward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-data-integration/pull/162
