### ISSUE TITLE
Add a new Sale Data Export solution

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#224]
Create a new Data Exporter for Sales base on the review design below

**Comment by harrisward** [comment]
Review the design: https://ivy-is.atlassian.net/wiki/spaces/SA/pages/1833795587/Sale+Data+Export

**Comment by fraserward** [comment]
Updated Export Job parameters 
Created new Sale Data Export Transformation
Updated CDAs for the same

**Comment by fraserward** [comment]
Pull request https://github.com/ivylabs/suitecrm-analytics/pull/232

**Comment by harrisward** [comment]
Added a new Sales Export to the Data Exporter.

**Comment by johnM2401** [comment]
Hi @harrisward, 
I had a question around this, that could use your insight!

The Sale Data Exporter appears to have a parameter for Invoice Status:
![image](https://user-images.githubusercontent.com/13675281/119855804-21a56e00-bf0a-11eb-96ab-6eb63a682c2d.png)


However, correct me if I'm wrong, but I think the F_SALES table only consists of "Paid" Invoice items, right?

If so, the "Invoice Status" parameter may be redundant as only "Paid" will return Sale Records
(Unless I have misunderstood its usage?)

Any thoughts?

**Comment by harrisward** [comment]
Yo uare correct. We will remove this parameter

**Comment by johnM2401** [comment]
Hey @harrisward 
It seems as though the Sale Data Export now returns 0 items, regardless of the Search Parameters.

I can see the equivalent data in the Agent Sales Report

However, when exporting Sale Data via the Exporter Tool, the CSV is always blank.
(Even if you don't change the Parameters, and use the default options)

This can be seen with both Demo Data and Live CRM Data.

<br>

(Please let me know if you'd rather I create a new issue ticket for this, or if it is more appropriate to move this item back)
