### ISSUE TITLE
New Average Call Duration Report

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#230]
Build a new Average Call Duration Report

Report Specifications:
[AverageCallDurationReportSpecifications.pdf](https://github.com/ivylabs/suitecrm-analytics/files/6548224/AverageCallDurationReportSpecifications.pdf)

Report Sample:
[AverageCallDurationReportSample.pdf](https://github.com/ivylabs/suitecrm-analytics/files/6548226/AverageCallDurationReportSample.pdf)

**Comment by fraserward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/271

**Comment by harrisward** [comment]
Damn fine. Works well

**Comment by harrisward** [comment]
@johnM2401 I've added the report specifications and sample to the main description

**Comment by johnM2401** [comment]
Hey @harrisward 
Adding a quick note, as requested:

The "Stacked" option is to be turned off for this Report, on both Bar/Line Charts, for readability

Thanks!
