### ISSUE TITLE
Change Data Export Output Type

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#234]
**Is your feature request related to a problem? Please describe.**
The Data Exporter results come out as Excel sheets at the moment and this is very slow to generate. We will allow the end user to export either w Styled XLS (which already exists) or When they choose No Styling they will get a CSV

**Describe the solution you'd like**

Default the Styling selector to "No Styling" (CSV) (Plugin)

Modify the ETL to output a CSV when No Styling option is selected
Modify the ETL to ZIP either the XLS or CSV into a zip file called export.zip

Modify the plugin the accept the ZIP file as a return data file instead of the XLS

**Comment by fraserward** [comment]
Updated transformation, jobs, dashboard data exporter.

Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/262

**Comment by johnM2401** [comment]
Looks good to me.

Defaulting to CSV, both CSV and XLS are being returned as a .zip file with the CSV/XLS file inside.
