### ISSUE TITLE
Improve Agent Case Performance Report Header

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#241]
**Is your feature request related to a problem? Please describe.**
The table headers are unclear

**Describe the solution you'd like**
Add sub table headers to the report
Tables Headers should be # for numbers and % for percentages

See the following screenshot as a reference:

![image](https://user-images.githubusercontent.com/6827832/117647817-62b92680-b185-11eb-8f04-e3b54b3764eb.png)

**Comment by fraserward** [comment]
Updated report headers.

Pull request: https://github.com/ivylabs/suitecrm-analytics/pull/249
