### ISSUE TITLE
Report Template has broken parameters

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#244]
**Describe the bug**
The Report template Parameters use the FILTERS CDA to generate their data. Since changes to the FILTERS CDA, the date parameters are broken. They point to YYYY-DD when it should be YYYY-MM in the Value field of the Parameter definition

**Component
What component does this bug relate to?
1. Report

**Solution File
SimpleFiltersCDADatasourceNoPassword

**To Reproduce**
1. Open the Report in Report Designer
2. Click Preview

**Expected behavior**
The Report Renders

**Comment by fraserward** [comment]
Updated parameters YYYY-DD to YYYY-MM

Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/250
