### ISSUE TITLE
missing output folder required for data exporter

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#25]
we need to create an output folder in the SuiteCRMAnalytics plugin folder to hold the data exports

**Comment by samus-aran** [comment]
I'm assuming I'm doing this right.

1. Navigate to Public > SuiteCRM Analytics > Tools > ExportSuiteCRMAnalyticsData.wcdf
2. Data Export (Select Data Export) * Case/Lead: Is there an ability to add more to this? Where can we do that?
3. A new windows pops up @ localhost:8080 asking for username/password *why do we need to add these details in?
4. Exported the Data named excelData.xlsx * Should this be filename/data specific
5. The file contains DATA & SHEET1 * Why does it have Data if there's nothing on it?

Does what it says on the tin :+1:

**Comment by harrisward** [comment]
Lots of good ideas. Lets open cases for each of them as they are not related directly to this case. Closed for now as the output folder has been created and tested.
