### ISSUE TITLE
CGG Sample Report is broken

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#257]
**Describe the bug**
Loading the default report throws parameter errors. We need to check the report output parameter as its blank when the report runs

**Component
What component does this bug relate to?
1. Report

**Solution File
SampleCGGReport

**To Reproduce**
1. Navigate to System/Resources/Samples
2. Execute the report

**Expected behavior**
It runs

**Comment by fraserward** [comment]
Updated default output stream.

**Comment by fraserward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/258

**Comment by harrisward** [comment]
Tested and working
