### ISSUE TITLE
Data Exporter Tool, Lead Export - The "Lead Created Period" Parameter appears to return 0 results if a Period is specified.

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#261]
**Describe the bug**

When using the Data Exporter Tool to export Lead Data, you are able to define parameters.

However, it appears the "Lead Created Period" parameter will always return 0 results, regardless of the period chosen.
(However, it works as expected when "All Periods" is chosen)

<br>

**Component**
What component does this bug relate to?
6. Other - Export Tool

<br>

**Solution File**
ExportSuiteCRMAnalyticsData.wcdf   -  Lead Data Export

<br>

**To Reproduce**

This appears to be an issue with both Live and Demo Data, however, to replicate:

1. Install Demo Data
2. Refresh the Caches on the Analytics end
2. Navigate to the Data Export Tool, and select "Lead Data Export"
3. Select the Parameter "September - 2020"
4. Export Data, and you will get 0 records returned
![image](https://user-images.githubusercontent.com/13675281/118653814-d12e6200-b7df-11eb-8aaa-019ff12dd9f2.png)

Despite there being plenty of leads created in September
![image](https://user-images.githubusercontent.com/13675281/118653872-dee3e780-b7df-11eb-9669-0bcb5187fd4a.png)
(From the F_LEAD_MANAGEMENT table)

<br>

**Expected behavior**
Exported data should return the correct result set, when a Period is chosen.

<br>

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Firefox 88.01

**Comment by harrisward** [comment]
This is because the SQL on the Table input for the transformation is using FLM.LEAD_CREATED_TK to filter the date parameter when it should be DD.`YYYY-MM`

This is because we pass the date format like YYYY-MM (2020-01) and NOT YYYYMM (202001) from the UI to the transformation

This bug is confirmed

**Comment by fraserward** [comment]
Transformation SQL updated.

Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/265
