### ISSUE TITLE
Data Exporter Tool, Lead Export - The "Lead Created Period" options don't appear to reflect the Live CRM data

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#267]
**Describe the bug**
The Lead Data Exporter shows Periods that don't reflect the Live Data.

eg:
- There are Parameter options for 2019, where there is no data.
- Where there are some Periods *with* data Data, such as March 2021, there is no Parameter.
(See screenshots below)

Oddly, the Available Parameters do seem to be the same as the ones used in the Case Data Export, (where the data matches)
Perhaps this is related?

<br>

**Component**
What component does this bug relate to?
6. Other - Data Exporter

<br>

**Solution File**
ExportSuiteCRMAnalyticsData.wcdf - Lead Data Export

<br>

**To Reproduce**
1. Create Records in various months for the Leads Module (Can be manipulated by changing the "date_entered" value in the Database
2. Push data from the CRM to the DWH, via the ./run script
3. Navigate to the Lead Exporter
4. Expand the "Lead Created Period" parameter, and compare available options to the CRM data

<br>

**Expected behavior**
The Periods available should match the Periods in which CRM Data exists.
However, the Exporter appears to show Periods where no Data exists, as well as not showing Periods where date exists.

<br>

**Screenshots**
As an example, the "Lead Created Period" parameter seems to show Periods for May/April/January 2021
![image](https://user-images.githubusercontent.com/13675281/118847770-0319f400-b8c6-11eb-831d-d6d2ca61da79.png)

However, the this does not match the available data.

ie, there are no records in April:
![image](https://user-images.githubusercontent.com/13675281/118848197-6efc5c80-b8c6-11eb-9c42-e537dfeffcca.png)

But there *are* records in March, where this was not a Parameter:
![image](https://user-images.githubusercontent.com/13675281/118848254-7cb1e200-b8c6-11eb-9cef-83cb8c6d9a3f.png)

<br>

Additionally, there are options for 2019:
![image](https://user-images.githubusercontent.com/13675281/118848391-9fdc9180-b8c6-11eb-9848-3b5df2efa49d.png)

But there is no data for 2019:
![image](https://user-images.githubusercontent.com/13675281/118848440-a8cd6300-b8c6-11eb-9f14-4e4deea12f68.png)

**Desktop (please complete the following information):**

    OS: Ubuntu 18.04
    Firefox 88.01

**Comment by fraserward** [comment]
Bug confirmed.

**Comment by fraserward** [comment]
Updated CDA file.

Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/269
