### ISSUE TITLE
GroupedLeadPerformance - Data in wrong columns

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-analytics#27]
When creating leads and assigning status (New & Assigned = work fine)  All other in wrong columns as below.

'In Process' goes to 'Dead'
'Converted' goes to 'In Process'
'Recycled' goes to 'Converted'
'Dead' goes to 'Recycled'

These filter selected at the time:

Filters:
--
Lead Source: All Lead Sources
Lead Country: All Lead Countries
Lead State: All Lead States
Campaign: All Campaigns
Campaign Status: All Campaign Status
Campaign Type: All Campaign Types

**Comment by harrisward** [comment]
Nice catch

**Comment by samus-aran** [comment]
Confirms that this has been resolved. :+1:
