### ISSUE TITLE
New Periodic Agent Country Sales Report

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#273]
Report Specification: 
[PeriodicAgentCountrySalesReportSpecifications.pdf](https://github.com/ivylabs/suitecrm-analytics/files/6617439/PeriodicAgentCountrySalesReportSpecifications.pdf)

Report Sample:
[PeriodicAgentCountrySalesReportSample.pdf](https://github.com/ivylabs/suitecrm-analytics/files/6617442/PeriodicAgentCountrySalesReportSample.pdf)

**Comment by fraserward** [comment]
Pull Request:  https://github.com/ivylabs/suitecrm-analytics/pull/274

**Comment by johnM2401** [comment]
Hey @harrisward 

Could you please provide the PDFs for this Report Specification, for when this is moved into the SA-QA Column?
That would be appreciated.

Thanks!

**Comment by harrisward** [comment]
@johnM2401 Done. Added to main description

**Comment by johnM2401** [comment]
@harrisward 
Ah, Thank you! 
Much appreciated!
