### ISSUE TITLE
Remove Invoice Status filter in Sales Export

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#281]
Remove the Invoice Status filter (mapping) from the Sales Export solution.

See this ticket: https://github.com/ivylabs/suitecrm-analytics/issues/224

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/283

**Comment by johnM2401** [comment]
Hey @harrisward 
It seems as though the Sale Data Export now returns 0 items, regardless of the Search Parameters.

I can see the equivalent data in the Agent Sales Report

However, when exporting Sale Data via the Exporter Tool, the CSV is always blank.
(Even if you don't change the Parameters, and use the default options)

This can be seen with both Demo Data and Live CRM Data.

<br>

(Please let me know if you'd rather I create a new issue ticket for this, or if it is more appropriate to move this item back)

**Comment by harrisward** [comment]
Well spotted. There was a mistake with a recent commit. Can you test again please @johnM2401
