### ISSUE TITLE
Add Data Exporter Documentation

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#285]
Add documentation on the Data Exporter to the Getting Started Guide

**Comment by johnM2401** [comment]
Hey @harrisward 

Data Exporter Documentation looks good, but have suggested one minor change against the Google Doc:

The last line of the section reads:
"If you select SuiteCRM Styling (Slow) this will output the data as an excel sheet also contained within is a zip."

<br>

However, to stay consistent with the line above it, I feel this line should read as follows:
"If you select SuiteCRM Styling (Slow) this will output the data as an **excel sheet** also contained within a zip file."

What are your thoughts?

**Comment by harrisward** [comment]
Can you add comments directly to the google document please @johnM2401 ?

**Comment by johnM2401** [comment]
Hey @harrisward 
Yep, I've also made these suggestions on the Google Doc
![image](https://user-images.githubusercontent.com/13675281/122400126-55a50980-cf73-11eb-92d4-d5c3648e5243.png)

Unless these aren't visible on your end?

**Comment by harrisward** [comment]
@johnM2401 I see them. Thank you

**Comment by rmcentee2020** [comment]
Hi Harris,

We have now made some minor amendments to this section within the documentation.

Thanks,

**Comment by rmcentee2020** [comment]
@harrisward
