### ISSUE TITLE
"Average Call Duration" Report - Cells in the Results table do not render if no data is found, rather than "0m"

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#286]
**Describe the bug**
When viewing the Average Call Duration Report, if a cell would have no data, it does not render the Cell itself rather than showing something like "0m"

<br>

**Component
What component does this bug relate to?
1. Report - Average Call Duration

<br>

**Solution File
AverageCallDuration.prpt

<br>

**To Reproduce**
1. In the CRM have Call Data for One or Two of: Leads / Cases / Opportunities, for a Month. (But not for all 3)
2. Run the ./run script to push this to the DWH
3. View the "Average Call Duration" report, and set the Call From/Call To Parameters to allow your data to show.

<br>

**Expected behavior**
If a Cell would have no Data, (or 0minutes), the Cell instead does not render

<br>

**Screenshots**
![image](https://user-images.githubusercontent.com/13675281/122423437-d3721080-cf85-11eb-8e96-91fa064f06b8.png)

<br>

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 88.01

**Comment by harrisward** [comment]
@johnM2401 Good spot. This is now fixed. Once its tested I will merge into master

Feature Branch: https://github.com/ivylabs/suitecrm-analytics/tree/feature-286
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/288

**Comment by johnM2401** [comment]
Hey @harrisward 
Is this good to go for me to test?

I've given it a go on the most recent master, but seems to be the same issue.
![image](https://user-images.githubusercontent.com/13675281/122568132-5a37f380-d041-11eb-832f-374dd756ea47.png)


Unless you want me to test this independently from the master branch?

**Comment by johnM2401** [comment]
Hey @harrisward 

Wasn't sure if you did indeed want me to have a look by pulling the feature-286 branch seperately, but I did so and it looks to be fine:
![image](https://user-images.githubusercontent.com/13675281/122756847-d7a47380-d28e-11eb-8539-7542d8bdad32.png)

Would be worth merging into master to test alongside the rest of the work, though.
