### ISSUE TITLE
Periodic Agent Country Sales Report - Formatting on Chart inconsistent with other Charts

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#291]
**Describe the bug**
The formatting of the Chart on the Periodic Agent Country Sales Report is inconsistent with some of the other Charts in Analytics.

- The X-axis appears to order the Years/Months in reverse order. (Going from Dec->Jan, 2021->2020)
Where, on other Charts, (Such as the Leads Dashboard & Average Call Duration), the Date is ordered Jan->Dec, 2020->2021

- The X-Axis is formatted like "2021 January", as opposed to how other charts in Analytics read.
(ie, Average Call Duration and "Leads by Source" on the Leads Dashboard will display the date as "2021-01")

See screenshots for examples.
<br>

**Component
What component does this bug relate to?
1. Report - Periodic Agent Country Sales Report

<br>

**Solution File
PeriodicAgentCountrySales.prpt

<br>

**To Reproduce**
1. Navigate to the Periodic Agent Country Sales Report, and view the Chart's Ordering and Formatting
2. Navigate to the Average Call Duration report, and compare the Chart's Ordering/Date Formatting to the Periodic Agent Country Report's Chart
3. Navigate to the Leads Performance Dashboard, and compare the "Leads by Source" chart's Ordering/Date Formatting to the Periodic Agent Country Report's Chart

<br>

**Expected behavior**
Formatting/Ordering should stay consistent through the Reports/Charts for ease of use.
(Personally, I feel that the "2021 - Jan" format would be best across any Charts that have Dates on the Axes, as it is clearest.
What are your thoughts?)

<br>

**Screenshots**
Periodic Agent Country Sales Chart:
![image](https://user-images.githubusercontent.com/13675281/122785781-91114200-d2ab-11eb-8a3b-4c197a721a06.png)

Average Call Duration Chart:
![image](https://user-images.githubusercontent.com/13675281/122785833-9c646d80-d2ab-11eb-8fea-f61e884cc121.png)

Leads by Source Chart:
![image](https://user-images.githubusercontent.com/13675281/122785908-abe3b680-d2ab-11eb-8e63-f356b65fac4b.png)

<br>

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 88.01

**Comment by harrisward** [comment]
@johnM2401 I've changed two reports to use the YYYY MMM format. I can't change the dashboards just now as its more connected to the date filters.

I've merged the change into master

**Comment by johnM2401** [comment]
Hey @harrisward 

Makes sense regarding the Dashboard.

Also, the formatting now appears to be "2021 Jan" on both Periodic Agent Country Sales and Average Call Duration reports.

<br>

Although, both Periodic Agent Country Sales and Average Call Duration charts now appear to be ordered from Dec->Jan
![image](https://user-images.githubusercontent.com/13675281/122897216-b0f34500-d341-11eb-99c3-41141f1f7120.png)

I have discussed with Ross, and we agree that the ordering would be clearer and easier to read, if it were the reverse.
(ie: Jan->Dec, 2020->2021)

(For both Periodic Agent Country Sales and Average Call Duration charts)


<br>

Also, it appears to be a fairly random order on the Average Call Duration Report:
![image](https://user-images.githubusercontent.com/13675281/122901066-1b59b480-d345-11eb-88e3-533394b088e2.png)

Not sure if this is related?
<br>

Would you be able to make this amendment?

**Comment by harrisward** [comment]
Fixed in the reports and merged into master @johnM2401
