### ISSUE TITLE
Periodic Agent Country Sales Report - The "Deleted" parameter does not filter out Deleted Invoices/Line Items when set to "Hide"

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#293]
**Describe the bug**
Periodic Agent Country Sales Report's "Deleted" parameter does not seem to filter out deleted Invoices/Line Items.

This does take place on the "Agent Sales" Report, so should be the same result on the "Periodic Agent Country Sales" report
<br>

**Component
What component does this bug relate to?
1. Report - Periodic Agent Country Sales Report 

<br>

**Solution File
PeriodicAgentCountrySales.prpt

<br>

**To Reproduce**
1. Create some Invoices, with multiple Line Items, in the CRM
2. Pull this to the DWH with the ./run script
3. Check this data is available in the Periodic Agent Country Sales Report.
4. In the CRM, delete a Line item on an Invoice
5. Pull this to the DWH with the ./run script
6. Toggle the "Deleted" parameter on the Periodic Agent Country Sales Report, and check that this deleted Line is no longer taken into consideration.
7. Delete this Invoice in the CRM
8. Pull this to the DWH with the ./run script
9. Again, Hide Deleted Items on the Periodic Agent Country Sales Report, and ensure that this full invoice is no longer taken into consideration

<br>

**Expected behavior**
Deleted Invoices/Line Items should not be taken into consideration, if the "Deleted" parameter is set to "Hide"
However, it currently does not hide deleted items.
<br>

**Screenshots**
For comparison, the Agent Sales Report does hide deleted items.

When set to "Show":
![image](https://user-images.githubusercontent.com/13675281/122943892-4fe26600-d36f-11eb-8802-cac4b7d6b221.png)

When set to "Hide":
![image](https://user-images.githubusercontent.com/13675281/122943995-5ffa4580-d36f-11eb-93a8-954eea1fb6b1.png)

And, on the Periodic Agent Country Sales Report:

When set to "Show":
![image](https://user-images.githubusercontent.com/13675281/122944083-6ee0f800-d36f-11eb-9126-ee6e793dd796.png)

When set to "Hide":
![image](https://user-images.githubusercontent.com/13675281/122944102-743e4280-d36f-11eb-9f0e-75b1845bec47.png)

<br>

**Desktop (please complete the following information):**
-    OS: Ubuntu 18.04
-    Browser: Firefox 88.01

**Comment by harrisward** [comment]
The issue was to do with the SQL query.

Fixed and merged into master @johnM2401
