### ISSUE TITLE
Periodic Agent Country Sales Report - Columns showing when no Data returned.

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#295]
**Describe the bug**
When the Periodic Agent Country Sales report would show 0 results, it appears to show some of the Columns, rather than simply just "No Data Available"

**Component
What component does this bug relate to?
1. Report - Periodic Agent Country Sales report 

**Solution File
PeriodicAgentCountrySales.prpt

**To Reproduce**
1. Navigate to the Periodic Agent Country Sales Report 
2. Set parameters so that 0 data is returned
3. View the "No data available" screen

**Expected behavior**
Like other reports, there should be no Columns shown on the Report when no data is returned

**Screenshots**
![image](https://user-images.githubusercontent.com/13675281/123136765-331b6080-d44b-11eb-9bc1-06eef59d48be.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 88.0.1

**Comment by harrisward** [comment]
Added logic to hide this row when no data is returned

**Comment by harrisward** [comment]
Feature Branch: https://github.com/ivylabs/suitecrm-analytics/tree/feature-295
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/296

**Comment by harrisward** [comment]
Please use the feature branch https://github.com/ivylabs/suitecrm-analytics/tree/feature-295. Once the fix has been confirmed I will merge the report into master @johnM2401

**Comment by johnM2401** [comment]
Hey @harrisward 
Looks good:
![image](https://user-images.githubusercontent.com/13675281/123251276-edaa7200-d4e2-11eb-992f-6837f7426c9e.png)

Can be merged into master.
