### ISSUE TITLE
Service Line Items - Service Lines do not display Quantity / Discount on the "Agent Sales" or "Periodic Agent Country Sales" Reports

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#299]
Hi, I'm not 100% sure if this would be more suited for the Data Integration board.
Please let me know if so, I'll move this over there.

<br>

**Describe the bug**
When Service Line Items are used on an Invoice in the CRM, the Quantity/Discount values are not detailed on either of the above reports.

See screenshots for examples
<br>

**Component**
What component does this bug relate to?
1. Report - Agent Sales Report & Periodic Agent Country Sales report 

**Solution File**
PeriodicAgentCountrySales.prpt & AgentSalesReport.prpt

<br>

**To Reproduce**
1. Create an Invoice in the CRM, and add some Service Lines.
2. On these Service Lines, add a Discount
3. Pull this to the CRM with the ./run script

4. View the "Agent Sales" report, and filter down to view this Invoice.
5. See that the Service Line Item shows a Quantity of 0, a Discount of 0. However, the "Total Revenue" still calculates correctly.
6. (See Screenshot 2 for an example)

7. View the Periodic Agent Country Sales Report, and filter down to see this invoice.
8. See that neither the "Quantity Sold" nor the "Total Discount" columns appear to take the Service Line Items into consideration
9. However, see that the "Total Revenue" column DOES include Service Line Items, which may mislead some users.
10. (See screenshot 3)

**Expected behavior**
The Quantity value will indicate how many Service Lines are on the Invoice, (if possible)
The Discount value will be pulled into Analytics for more accurate reporting.

<br>

**Screenshots**

Invoice Created:
![image](https://user-images.githubusercontent.com/13675281/123289532-74be1100-d508-11eb-80cb-902bd86763d5.png)

However, Agent Sales Report shows as:
![image](https://user-images.githubusercontent.com/13675281/123287053-5bb46080-d506-11eb-9a63-5741ff959901.png)

And Periodic Agent Country Sales shows as:
![image](https://user-images.githubusercontent.com/13675281/123287097-64a53200-d506-11eb-87d0-8d9b608aa427.png)

<br>

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 88.0.1

**Comment by harrisward** [comment]
@johnM2401 This looks like a data issue. In the source system if we have a Service Line then no quantity is set so we pull through 0. It sounds like what we might di is set the quantity to 1 to represent one service line sold. With this value we would multiply the quantity by discount which would then also return the discount value.

Can we confirm that we should set adhoc service line items in out data warehouse to a default quantity of 1?

**Comment by johnM2401** [comment]
Hey @harrisward 

Having a Quantity of 1 makes sense to me.

I don't believe Service Lines have a Quantity value in the CRM, so defaulting to a Quantity of 1 per line for calculation purposes sounds like the best way forward.

**Comment by harrisward** [comment]
@johnM2401 Agreed. I will raise a ticket in SuiteCRM Data Integration as its an ETL issue and refer to this one which I will close.

The ticket in SuiteCRM Data Integration is https://github.com/ivylabs/suitecrm-data-integration/issues/176
