### ISSUE TITLE
Develop Base Mondrian Schema

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#30]
Develop a few base cubes.. The sales cube features row based security.

**Comment by harrisward** [comment]
Developed a foundation Mondrian schema based on Leads and Leads Tracking. Not for use with any existing solutions but committed to 1.1 for now

**Comment by harrisward** [comment]
Need to find the correct place to commit this file so its imported during installation

**Comment by harrisward** [comment]
Made a start on this and committed it to the root of the install directory. Not published to the BIServer yet as its not needed for anything

**Comment by harrisward** [comment]
Added TRUST_USER functionality to support CGG report requests. Need to update all JS files and PRPTs to use encoded filenames

**Comment by harrisward** [comment]
Multiple Roles assigned to a single user is causing the rules to be broken.

**Comment by fraserward** [comment]
Tested by SA.
