### ISSUE TITLE
Average Call Duration - Average Total Row doesn't match with the Month Row, The Modules appear to be misaligned

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#305]
**Describe the bug**
It appears that the Cases/Leads Modules are misaligned for the Month and "YYYY Average Total" rows on the Average Call Duration Report's Tables

See screenshots for examples.

<br>

**Component
What component does this bug relate to?
1. Report - Average Call Duration Report

<br>

**Solution File
AverageCallDuration.prpt

<br>

**To Reproduce**
1. Add Call data for either Cases or Leads, so that an Average is calculated
2. Pull this to the dwh with the ./run script
3. View the Average Call Duration Report

<br>

**Expected behavior**
The Data should match with the correct Module

<br>

**Screenshots**
I only have Call data for Cases:
![image](https://user-images.githubusercontent.com/13675281/123606264-a1b64080-d7f4-11eb-8b76-0ed20fd071bc.png)

But the "Total Average" shows below Leads

If I then add Call data to Leads, the Average appears below Cases:
![image](https://user-images.githubusercontent.com/13675281/123606348-b85c9780-d7f4-11eb-92b1-cf7396009f00.png)

**Comment by harrisward** [comment]
Good spot. Fixed. Can you test the branch please @johnM2401

**Comment by harrisward** [comment]
Feature Branch: https://github.com/ivylabs/suitecrm-analytics/tree/feature-305
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/306

**Comment by johnM2401** [comment]
Hey @harrisward 

Looks good, averages all adding up and aligned with the correct columns now

Can be merged to master
