### ISSUE TITLE
Dashboard contains other not necessary dashboard file formats 

### ISSUE THREAD

**Issue by samus-aran** [ivylabs/suitecrm-analytics#4]
Steps to reproduce:
1. install SuiteCRM Analytics server
2. Successfully login
3. Navigate to Browse Files > Public > SuiteCRM Analytics > Dashboard

Expected Behaviour
1. Only see a single Report of the file format .wcdf

Actual Behaviour
1. See multiple Reports that provide no additional (unknown) functionality

![analytics_bug](https://user-images.githubusercontent.com/4041275/64163444-2de5bf80-ce39-11e9-9aee-341079abc25c.png)

**Comment by harrisward** [comment]
Not a bug. Each dashboard solution contains a minimum of 2 to 3 files. I may look for a solution to hide the other files
