### ISSUE TITLE
Check all Report Dropdown Ordering

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#63]
Reorder dropdowns based on real life ordering (New, Assigned, Closed) or alphabetical order if not natural order

**Comment by fraserward** [comment]
All reports checked - satis, other than 'Lead State' in 'Grouped Lead Performance' report where one state 'North East Derbyshire' appears out of order (2nd in list - above 'A's'

**Comment by harrisward** [comment]
Not a pulldown issue but a demo data issue
