### ISSUE TITLE
New Lead Performance Report

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#7]
The new Lead Performance Report will be more dynamic than the existing Agent Lead Performance Report in that the row data can be grouped by other data than just agents. It will use SQL scripting to accomplish this

**Comment by samus-aran** [comment]
Testing:
Firefox (71.0 (64-bit))
Data Rows (30+ Agents vs 10K+ Leads)

Comments:
- I can see there's a new Report Style called **Custom** How can this be applied?

**Comment by samus-aran** [comment]
Just looking at other issues and I'm not sure how to confirm that I am using the 1.1 branch.

This is the report I see.

![FireShot Capture 001 - SuiteCRM Analytics - Agent Lead Performance](https://user-images.githubusercontent.com/4041275/71011436-4d051600-20e5-11ea-886b-101a55a03b19.png)

**Comment by samus-aran** [comment]
Oh! Is this, GroupedLeadPerformance?

Yeah, I agree it looks nice and is grouped/filtered by multiple values - Nice.

![FireShot Capture 001 - SuiteCRM Analytics - Group Lead Performance](https://user-images.githubusercontent.com/4041275/71011876-1380da80-20e6-11ea-9681-f626c42e4c3a.png)

Comments:
- It would be good to have the complete Total of all the Leads at the end so we can have reference of how many leads have been reported on.
- The sub-total is slightly off centred (see screenshot) (Only Firefox)

**Comment by harrisward** [comment]
Alignment looks fine on FF 72.02 64Bit

**Comment by harrisward** [comment]
Need to add totals

**Comment by harrisward** [comment]
Added Totals to the report
