### ISSUE TITLE
Agent Opportunity Performance Report - Numbers don't match

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#71]
See below. The chart data does not match the report data:

![image](https://user-images.githubusercontent.com/6827832/90398620-a5841d00-e091-11ea-83cc-de72fdad1f03.png)

**Comment by harrisward** [comment]
this report needs review as it has a Opportunity Sales Stage filter yet displays the sales stage in the report columns

**Comment by fraserward** [comment]
QA - Good
