### ISSUE TITLE
Invoice Report Discount calculation issue

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#74]
The discount field is displayed as a percentage. Its looks like its never a percentage but instead a dollar value amount.

Also the tax value field is displayed as 0.175 when in fact it should be a percentage like 17.5%

**Comment by harrisward** [comment]
Removed the Percentage from the Discount Amount. Need to open a new ticket for the tax calculation as the tax field cannot be formatted with a number format. Its is a string for some reason.

**Comment by fraserward** [comment]
QA - Good
