### ISSUE TITLE
Invoice - Tax format cannot be applied

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#75]
We cannot apply a percentage tax format to the tax value field. It is returned in the report as string for some reason. We need to change 0.175 (string) to 17.5% (number format)

**Comment by harrisward** [comment]
Need to convert the string field to a number via the report SQL query. Will look into changing this data type in the table later

**Comment by harrisward** [comment]
Here is a sample Query:

SELECT 
	CONVERT(FIM.INVOICE_LINE_VAT_VALUE, DECIMAL) AS INVOICE_LINE_VAT_VALUE_NOT_WORKING
	,FIM.INVOICE_LINE_VAT_VALUE
	,CONVERT("560", DECIMAL)
FROM F_INVOICE_MANAGEMENT FIM
INNER JOIN D_INVOICES DI
	ON FIM.INVOICE_TK = DI.INVOICE_TK
INNER JOIN D_PRODUCTS DP
	ON FIM.PRODUCT_TK = DP.PRODUCT_TK
INNER JOIN D_USERS DU
	ON FIM.ASSIGNED_USER_TK = DU.USER_TK
INNER JOIN D_ACCOUNTS DA
	ON FIM.BILLING_ACCOUNT_TK = DA.ACCOUNT_TK;

**Comment by harrisward** [comment]
Reworked the query to CAST the value

**Comment by fraserward** [comment]
QA - Good
