### ISSUE TITLE
pInvoiceNumberFilterQuery Order problem

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#76]
The query for this filter SQL is not returning the correct order. When the two queries are unions the order of the invoice number is incorrect

**Comment by harrisward** [comment]
Query.

SELECT 'All Invoice Numbers' AS INVOICE_NUMBER, 1 AS ORDINAL
UNION
SELECT DISTINCT(INVOICE_NUMBER), 2 AS ORDINAL 
FROM D_INVOICES
ORDER BY 2,1

**Comment by harrisward** [comment]
Modified the query and getting the correct result

**Comment by fraserward** [comment]
QA - Good
