### ISSUE TITLE
Remove hoverhand icon for breadcrumb

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#86]
When the user hovers over the breadcrumb items they get the hoverhand. Remove this as the breadcrumb links to nothing at the momoent

**Comment by harrisward** [comment]
This looks to be fixed. Need to double check

**Comment by harrisward** [comment]
Must have been removed in an earlier version. Cannot recreate the issue on 1.2. There are no a hrefs on the breadcrumb anymore

**Comment by fraserward** [comment]
Tested by SA.
