### ISSUE TITLE
Update the Date Range Components to reflect the selected Date Range Selector Value

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#87]
When the user selects a predefined date range from the Date Range Dropdown (last 6 months for example), the disabled Date from and Date To fields of the Custom Range selection should be updated to reflect this prior to the refresh button being clicked. This will avoid any confusion as to what range the user is refreshing the data for.

**Comment by fraserward** [comment]
Tested by SA.
