### ISSUE TITLE
Work around static username / password in CGG charts for PRPTs

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-analytics#88]
Need to find a workaround to allow an  admin password change to be reflected in the prpt CGG chart executions

**Comment by harrisward** [comment]
Its possible to add memory authentication to handle this.

https://help.pentaho.com/Documentation/8.0/Setup/Administration/User_Security/Implement_Advanced_Security/080

**Comment by harrisward** [comment]
Added memory based authentication. See ticket #98 

Still need to add logic to inject the reporting user generated password into each PRPT. This will work for CGG authentication but the CDA authentication password is encrypted. Need to investigate this encryption type

**Comment by harrisward** [comment]
I think we can completely remove the CDA username / password combination from the PRPTS as the CDA endpoint details are picked up while running on the server. Refer to the report template documentation in the templates folder

**Comment by harrisward** [comment]
Memory based authentication will not work for role based mondrian security as it only passes a single user to the BIServer to generate the CGG chart. Instead we can update all the reports to utilise the TRUST_USER parameter

**Comment by harrisward** [comment]
Refer to #30

**Comment by harrisward** [comment]
Added Trusted User to chart parameter URL.

Test all reports with charts after changing the admin password. Test with other users also.

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/216

**Comment by fraserward** [comment]
Tested. Working.
